apiVersion: cortex.opstrace.io/v1alpha1
kind: Cortex
metadata:
  name: cortex-sample
spec:
  image: "cortexproject/cortex:v1.9.0"

  config:
    server:
      grpc_server_max_recv_msg_size: 41943040
      grpc_server_max_send_msg_size: 41943040
    memberlist:
      max_join_backoff: 1m
      max_join_retries: 20
      min_join_backoff: 1s
    query_range:
      split_queries_by_interval: 24h
    limits:
      compactor_blocks_retention_period: 192h
      ingestion_rate: 100000
      ingestion_rate_strategy: local
      ingestion_burst_size: 200000
      max_global_series_per_user: 10000000
      max_series_per_user: 5000000
      accept_ha_samples: true
      ha_cluster_label: prometheus
      ha_replica_label: prometheus_replica
      ruler_tenant_shard_size: 3
    ingester:
      lifecycler:
        join_after: 30s
        observe_period: 30s
        num_tokens: 512
    blocks_storage:
      tsdb:
        retention_period: 6h
      backend: s3
      s3:
        bucket_name: cortex-operator-example-209f-data
        endpoint: s3.us-west-2.amazonaws.com
    configs:
      database:
        uri: https://someuri.com
        migrations_dir: /migrations
    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: cortex-operator-example-209f-config
        endpoint: s3.us-west-2.amazonaws.com
    ruler_storage:
      backend: s3
      s3:
        bucket_name: cortex-operator-example-209f-config
        endpoint: s3.us-west-2.amazonaws.com

  runtime_config:
    ingester_limits:
      max_inflight_push_requests: 1000

  alertmanager_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
  compactor_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
    datadir_size: 30Gi
    storage_class_name: pd-ssd
  distributor_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
    - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
      value: foo:1234
  ingester_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
    - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
      value: foo:1234
    datadir_size: 30Gi
    storage_class_name: pd-ssd
  querier_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
      value: foo:1234
  query_frontend_spec:
    replicas: 2
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
    - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
      value: foo:1234
  ruler_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
    - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
      value: foo:1234
  store_gateway_spec:
    replicas: 3
    env:
    - name: JAEGER_AGENT_HOST
      value: foo
    datadir_size: 30Gi
    storage_class_name: pd-ssd

  memcached:
    image: memcached:1.6.9-alpine
    chunks_cache_spec:
      replicas: 2
      max_item_size: 2m
      memory_limit: 4096
    index_queries_cache_spec:
      replicas: 2
      max_item_size: 2m
      memory_limit: 4096
    index_writes_cache_spec:
      replicas: 2
      max_item_size: 2m
      memory_limit: 4096
    metadata_cache_spec:
      replicas: 2
      max_item_size: 2m
      memory_limit: 4096
    results_cache_spec:
      replicas: 2
      max_item_size: 2m
      memory_limit: 4096

  service_account_spec:
    annotations: {}
